### ISSUE TITLE
Query: Population Largest to Smallest

### ISSUE THREAD

**Issue by decfisher** [decfisher/Napier-GA-Group-H#10]
- All the countries in the **world** organised by largest population to smallest.
- All the countries in a **continent** organised by largest population to smallest.
- All the countries in a **region** organised by largest population to smallest.

**Comment by Tide44-cmd** [comment]
Additionally, the following information should be accessible to the organisation:

The population of the world.
The population of a continent.
The population of a region.
The population of a country.
The population of a district.
The population of a city.

**Comment by Tide44-cmd** [comment]
getCountriesByPopulation()
getCountriesByPopulation(String Continent)
getCountriesByPopulation(String Continent, String Region)
printCountries(ArrayList<Country> countries, String type)
