### ISSUE TITLE
Report: By Country

### ISSUE THREAD

**Issue by decfisher** [decfisher/Napier-GA-Group-H#11]
A country report **requires** the following columns:
- Code
- Name
- Continent
- Region
- Population
- Capital

**Comment by Tide44-cmd** [comment]
A country report requires the following columns:

Code.
Name.
Continent.
Region.
Population.
Capital.

**Comment by decfisher** [comment]
As a member of organisation X
I want to view a report of all countries in the world
So that I can identify information about each country in the world

**Acceptance Criteria**
Given I run the query
When I provide **one** parameter
Then I will see a list of all **countries** in the world along with their corresponding information

The query should filter the results using parameters provided by the user in order to display what the user requires to see.
