### ISSUE TITLE
Report: By Population

### ISSUE THREAD

**Issue by decfisher** [decfisher/Napier-GA-Group-H#14]
For the population reports, the following information is **required**:
- The name of the **continent/region/country**
- The total population of the **continent/region/country**
- The total population of the **continent/region/country living in cities (including a %)**
- The total population of the **continent/region/country not living in cities (including a %)**

**Comment by Tide44-cmd** [comment]
Population Report
For the population reports, the following information is requested:

The name of the continent/region/country.
The total population of the continent/region/country.
The total population of the continent/region/country living in cities (including a %).
The total population of the continent/region/country not living in cities (including a %).

**Comment by decfisher** [comment]
As a member of organisation X
I want to view a report of a **continent/region/country's** population
So that I can identify population information about the **continent/region/country**

**Acceptance Criteria**
Given I run the query
When I provide **two** parameters
Then I will see population information about the **continent/region/country** that was provided

The query should filter the results using parameters provided by the user in order to display what the user requires to see.
