### ISSUE TITLE
[BUG]: Messy Code

### ISSUE THREAD

**Issue by decfisher** [decfisher/Napier-GA-Group-H#22]
### Contact Details

40509526@live.napier.ac.uk

### Describe the bug

Code hard to read/understand, would be better if code can be cleaned up and marked with more comments or objects separated out of functions to avoid duplication.

### Version

0.1-alpha-5 (Pre-release v5.0)

### Code of Conduct Agreement

- [X] I have read and acknowledged the [Code of Conduct](https://github.com/decfisher/Napier-GA-Group-H/blob/master/CODE_OF_CONDUCT.md) for this project

**Comment by Tide44-cmd** [comment]
Additional methods have been written to remove code duplication
