### ISSUE TITLE
[BUG]: Reporter Class Unit Tests

### ISSUE THREAD

**Issue by decfisher** [decfisher/Napier-GA-Group-H#29]
### Contact Details

40509526@live.napier.ac.uk

### Describe the bug

Not all areas of Reporter class covered.

### Version

0.1-alpha-5 (Pre-release v5.0)

### Code of Conduct Agreement

- [X] I have read and acknowledged the [Code of Conduct](https://github.com/decfisher/Napier-GA-Group-H/blob/master/CODE_OF_CONDUCT.md) for this project

**Comment by Tide44-cmd** [comment]
Update existing Unit tests to match the new method names and reports
